[project]
name = "food-planer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Andreas Pommerencke", email = "anpom21@student.sdu.dk" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
food-planer = "food_planer:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
